### ISSUE TITLE
Can't access GHCR image after the GA changes

### ISSUE THREAD

**Issue by oguzhan-yilmaz** [DazWilkin/crtsh-exporter#18]
Hey, after updating the Github Actions, I can't access the docker images through ghcr.io

Package page show 404 error: <https://github.com/DazWilkin/crtsh-exporter/pkgs/container/crtsh-exporter>

- (example) Public Package image tags: <https://explore.ggcr.dev/?repo=ghcr.io%2Fdazwilkin%2Fgcp-exporter>
- crtsh-exporter image tags: <https://explore.ggcr.dev/?repo=ghcr.io%2Fdazwilkin%2Fcrtsh-exporter>
  ```
  failed: GET https://ghcr.io/token?scope=repository%3Adazwilkin%2Fcrtsh-exporter%3Apull&service=ghcr.io: UNAUTHORIZED: authentication required
  ```

Perhaps the github package visibility was changed to `private`?

**Comment by DazWilkin** [comment]
I was unable to get `multi-platform-docker-build` to work.

I am able to get the Action to run successfully but:

```bash
podman pull ghcr.io/dazwilkin/crtsh-exporter:latest
```
```
Trying to pull ghcr.io/dazwilkin/crtsh-exporter:latest...
Error: choosing an image from manifest list docker://ghcr.io/dazwilkin/crtsh-exporter:latest: no image found in image index for architecture amd64, variant "", OS linux 
```
And:
```bash
docker pull ghcr.io/dazwilkin/crtsh-exporter:latest
```
```
latest: Pulling from dazwilkin/crtsh-exporter
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by oguzhan-yilmaz** [comment]
@DazWilkin Can you verify if the package is public? I'd like to help debug but I get auth errors

**Comment by DazWilkin** [comment]
I've added you as a package reader so you *should* be able to `pull`

**Comment by DazWilkin** [comment]
It's a non-working day for me and tomorrow I have some commitments in the morning

**Comment by oguzhan-yilmaz** [comment]
Thanks for sparing your free time and read access. I managed to fix the issues and created a PR #20  

Hopefully it'll fix the issue

**Comment by DazWilkin** [comment]
Thank you for solving this.

I will try to review after walking with my dog and before my appointments this morning.

**Comment by oguzhan-yilmaz** [comment]
Thanks for merging the PR, I can pull and run the image with `:latest` tag.

**Comment by DazWilkin** [comment]
And `cosign verify` now works too.

There was a bug in the reference to the step's output value.

Thank you for your contributions.
